//Users
export const SET_ALL_USERS = "SET_ALL_USERS";
export const USER_UPDATED = "USER_UPDATED";
export const USER_ADDED = "USER_ADDED";
export const USER_DELETED = "USER_DELETED";
export const USER_UPLOADING = "USER_UPLOADING";
export const SET_PERMISSION_LEVEL = "SET_PERMISSION_LEVEL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
